version: "3"
services:
    rabbitmq-server:
        build: ./rabbitmq-server
    packet-handler:
        build: ./packet-handler
        ports:
            - "3000:3000/udp"
        command: ["dockerize", "-wait", "tcp://rabbitmq-server:5672", "-timeout", "60s", "go", "run", "main.go"]
    game-data:
        build: ./game-data
    spell-handler:
        build: ./spell-handler
    movement-handler:
        build: ./movement-handler
        command: ["dockerize", "-wait", "tcp://rabbitmq-server:5672", "-timeout", "60s", "npm", "start"]